### ISSUE TITLE
Collaborate?

### ISSUE THREAD

**Issue by ariutta** [aleofreddi/svgpan#34]
Hello and thanks for your work in this area.

Based on your library, I [created a version](https://github.com/ariutta/svg-pan-zoom#related-work) for use with the HTML `script` element, instead of the SVG `script` element. Since then, @bumbu has taken the lead on the project. Since the work started with you and it is challenging to keep up with cross-browser compatibility issues, I'd welcome the chance to collaborate!

Also, it'd be great to hear your thoughts on [this issue](https://github.com/ariutta/svg-pan-zoom/issues/98). Trying to solve too many use cases can lead to bloat, and I'd like to keep the core small and focused.

**Comment by aleofreddi** [comment]
Hi Anders,
I agree and I like the idea of adding a plugin mechanism, keep on doing 👍

Cheers,

   Andrea

**Comment by ariutta** [comment]
Great! How do you and @bumbu want to manage this? I see three options:

1. I sent you an invite to the [svg-pan-zoom repo](https://github.com/ariutta/svg-pan-zoom), so you can make edits there. (@bumbu has put in a lot of thought and work on this project, so I check with him before making any major edits.)
2. If you or @bumbu prefer, I'm open to transferring the repo to whoever is doing the most work on it, as long as we can do that without breaking anything that depends on the current link.
3. We could create a GH organization for this project and any related work.

The easiest option might be 1 for now, and 3 once we're ready to release a new version with a plugin system.

Cheers!

**Comment by aleofreddi** [comment]
Option 1 will do!

**Comment by ariutta** [comment]
Sounds good! I'll go ahead and close this issue now.
